# Generated by Django 6.0.6 on 2026-06-23 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day_index', models.PositiveIntegerField(help_text='0-based day number within the trip.')),
                ('from_location', models.CharField(blank=True, max_length=255)),
                ('to_location', models.CharField(blank=True, max_length=255)),
                ('total_miles_driving', models.FloatField(default=0)),
                ('totals', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['trip', 'day_index'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('current_cycle_used_hours', models.FloatField(default=0, help_text='Hours already used in the 70hr/8day cycle at trip start.')),
                ('current_coords', models.JSONField(blank=True, null=True)),
                ('pickup_coords', models.JSONField(blank=True, null=True)),
                ('dropoff_coords', models.JSONField(blank=True, null=True)),
                ('total_distance_miles', models.FloatField(blank=True, null=True)),
                ('total_duration_hours', models.FloatField(blank=True, null=True)),
                ('route_geometry', models.JSONField(blank=True, help_text='GeoJSON-style list of [lon, lat] points for the map.', null=True)),
                ('stops', models.JSONField(blank=True, help_text='Ordered stops: pickup, fuel, rests, breaks, dropoff.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LogSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OFF', 'Off Duty'), ('SB', 'Sleeper Berth'), ('D', 'Driving'), ('ON', 'On Duty (not driving)')], max_length=3)),
                ('start_minute', models.PositiveIntegerField(help_text='Minutes from local midnight (0-1440).')),
                ('end_minute', models.PositiveIntegerField(help_text='Minutes from local midnight (0-1440).')),
                ('location', models.CharField(blank=True, max_length=255)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('log_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='trips.logsheet')),
            ],
            options={
                'ordering': ['log_sheet', 'start_minute'],
            },
        ),
        migrations.AddField(
            model_name='logsheet',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_sheets', to='trips.trip'),
        ),
        migrations.AlterUniqueTogether(
            name='logsheet',
            unique_together={('trip', 'day_index')},
        ),
    ]
