# Generated by Django 6.0.6 on 2026-06-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='timezone',
            field=models.CharField(blank=True, help_text='IANA zone of the current location; all log times are in it.', max_length=64),
        ),
    ]
